
CC = gcc
CFLAGS = -g -Wall -mcpu=common
RANLIB = ranlib

INCLUDES = Ilib.h

all: $(INCLUDES)

Ilib.h:
	ln ../src/Ilib.h .

install:
	@echo "Install not done from `pwd`"

clean:
	@echo "Cleaning in `pwd`"
	rm -f $(INCLUDES)

makefiles:

makefile:

# START DEPENDENCIES
