/*
 * This file was generated automatically by xsubpp version 1.9507 from the 
 * contents of Ilib.xs. Do not edit this file, edit Ilib.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Ilib.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <Ilib.h>

static int
not_here(char *s)
{
    croak("%s not implemented on this architecture", s);
    return -1;
}

static char *
str_constant(char *name)
{

  switch ( *name ) {
    case 'I':
      if (strEQ(name, "ILIB_URL"))
        return ILIB_URL;
      if (strEQ(name, "ILIB_VERSION"))
        return ILIB_VERSION;
      if (strEQ(name, "ILIB_VERSION_DATE"))
        return ILIB_VERSION_DATE;
    break;
  }

  return "";
}

static double
constant(char *name, int arg)
{
    errno = 0;
    switch (*name) {
    case 'A':
	break;
    case 'B':
	break;
    case 'C':
	break;
    case 'D':
	break;
    case 'E':
	break;
    case 'F':
	break;
    case 'G':
	break;
    case 'H':
	break;
    case 'I':
	if (strEQ(name, "ILIB_URL"))
	    return atof(ILIB_URL);
	if (strEQ(name, "ILIB_VERSION"))
	    return atof(ILIB_VERSION);
	if (strEQ(name, "ILIB_VERSION_DATE"))
	    return atof(ILIB_VERSION_DATE);
	if (strEQ(name, "ILIB_MAJOR_VERSION"))
	    return ILIB_MAJOR_VERSION;
	if (strEQ(name, "ILIB_MICRO_VERSION"))
	    return ILIB_MICRO_VERSION;
	if (strEQ(name, "ILIB_MINOR_VERSION"))
	    return ILIB_MINOR_VERSION;

	if (strEQ(name, "IOPTION_ASCII"))
	    return IOPTION_ASCII;
	if (strEQ(name, "IOPTION_GRAYSCALE"))
	    return IOPTION_GRAYSCALE;
	if (strEQ(name, "IOPTION_GREYSCALE"))
	    return IOPTION_GREYSCALE;
	if (strEQ(name, "IOPTION_INTERLACED"))
	    return IOPTION_INTERLACED;
	if (strEQ(name, "IOPTION_NONE"))
	    return IOPTION_NONE;

	if (strEQ(name, "IBLACK_PIXEL"))
	    return IBLACK_PIXEL;
	if (strEQ(name, "IWHITE_PIXEL"))
	    return IWHITE_PIXEL;

	if (strEQ(name, "INUM_FORMATS"))
	    return INUM_FORMATS;
	if (strEQ(name, "IFORMAT_GIF"))
	    return IFORMAT_GIF;
	if (strEQ(name, "IFORMAT_PPM"))
	    return IFORMAT_PPM;
	if (strEQ(name, "IFORMAT_PGM"))
	    return IFORMAT_PGM;
	if (strEQ(name, "IFORMAT_PBM"))
	    return IFORMAT_PBM;
	if (strEQ(name, "IFORMAT_XPM"))
	    return IFORMAT_XPM;
	if (strEQ(name, "IFORMAT_XBM"))
	    return IFORMAT_XBM;
	if (strEQ(name, "IFORMAT_PNG"))
	    return IFORMAT_PNG;
	if (strEQ(name, "IFORMAT_JPEG"))
	    return IFORMAT_JPEG;

	if (strEQ(name, "ILINE_SOLID"))
	    return ILINE_SOLID;
	if (strEQ(name, "ILINE_ON_OFF_DASH"))
	    return ILINE_ON_OFF_DASH;
	if (strEQ(name, "ILINE_DOUBLE_DASH"))
	    return ILINE_DOUBLE_DASH;

	if (strEQ(name, "IFILL_SOLID"))
	    return IFILL_SOLID;
	if (strEQ(name, "IFILL_TILED"))
	    return IFILL_TILED;
	if (strEQ(name, "IFILL_STIPPLED"))
	    return IFILL_STIPPLED;
	if (strEQ(name, "IFILL_OPAQUE_STIPPLED"))
	    return IFILL_OPAQUE_STIPPLED;

	if (strEQ(name, "ITEXT_NORMAL"))
	    return ITEXT_NORMAL;
	if (strEQ(name, "ITEXT_ETCHED_IN"))
	    return ITEXT_ETCHED_IN;
	if (strEQ(name, "ITEXT_ETCHED_OUT"))
	    return ITEXT_ETCHED_OUT;
	if (strEQ(name, "ITEXT_SHADOWED"))
	    return ITEXT_SHADOWED;

	if (strEQ(name, "ITEXT_LEFT_TO_RIGHT"))
	    return ITEXT_LEFT_TO_RIGHT;
	if (strEQ(name, "ITEXT_BOTTOM_TO_TOP"))
	    return ITEXT_BOTTOM_TO_TOP;
	if (strEQ(name, "ITEXT_TOP_TO_BOTTOM"))
	    return ITEXT_TOP_TO_BOTTOM;

	break;

    case 'J':
	break;
    case 'K':
	break;
    case 'L':
	break;
    case 'M':
	break;
    case 'N':
	break;
    case 'O':
	break;
    case 'P':
	break;
    case 'Q':
	break;
    case 'R':
	break;
    case 'S':
	break;
    case 'T':
	break;
    case 'U':
	break;
    case 'V':
	break;
    case 'W':
	break;
    case 'X':
	break;
    case 'Y':
	break;
    case 'Z':
	break;
    }
    errno = EINVAL;
    return 0;

not_there:
    errno = ENOENT;
    return 0;
}

typedef IImage Ilib__IImage;
typedef IGC Ilib__IGC;
typedef IColor Ilib__IColor;
typedef void * Ilib__IFont;

#line 194 "Ilib.c"
XS(XS_Ilib_constant)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Ilib::constant(name,arg)");
    {
	char *	name = (char *)SvPV(ST(0),PL_na);
	int	arg = (int)SvIV(ST(1));
	double	RETVAL;

	RETVAL = constant(name, arg);
	ST(0) = sv_newmortal();
	sv_setnv(ST(0), (double)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_str_constant)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Ilib::str_constant(name)");
    {
	char *	name = (char *)SvPV(ST(0),PL_na);
	char *	RETVAL;

	RETVAL = str_constant(name);
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_IErrorString)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Ilib::IErrorString(err)");
    {
	int	err = (int)SvIV(ST(0));
	char *	RETVAL;
#line 201 "Ilib.xs"
	RETVAL = IErrorString ( err );
#line 238 "Ilib.c"
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_ICreateImage)
{
    dXSARGS;
    if (items < 0 || items > 3)
	croak("Usage: Ilib::ICreateImage(width=480, height=640, options=0)");
    {
	unsigned int	width;
	unsigned int	height;
	unsigned int	options;
	Ilib__IImage	RETVAL;

	if (items < 1)
	    width = 480;
	else {
	    width = (unsigned int)SvUV(ST(0));
	}

	if (items < 2)
	    height = 640;
	else {
	    height = (unsigned int)SvUV(ST(1));
	}

	if (items < 3)
	    options = 0;
	else {
	    options = (unsigned int)SvUV(ST(2));
	}
#line 211 "Ilib.xs"
	RETVAL = ICreateImage ( width, height, options );
#line 275 "Ilib.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Ilib::IImage", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_IWriteImageFile)
{
    dXSARGS;
    if (items < 2 || items > 4)
	croak("Usage: Ilib::IWriteImageFile(fp, image, format=IFORMAT_GIF, options=0)");
    {
	FILE *	fp = IoIFP(sv_2io(ST(0)));
	Ilib__IImage	image;
	unsigned int	format;
	unsigned int	options;
	int	RETVAL;

	if (sv_derived_from(ST(1), "Ilib::IImage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    image = (Ilib__IImage) tmp;
	}
	else
	    croak("image is not of type Ilib::IImage");

	if (items < 3)
	    format = IFORMAT_GIF;
	else {
	    format = (unsigned int)SvUV(ST(2));
	}

	if (items < 4)
	    options = 0;
	else {
	    options = (unsigned int)SvUV(ST(3));
	}
#line 222 "Ilib.xs"
	RETVAL = IWriteImageFile ( fp, image, format, options );
#line 314 "Ilib.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_ICreateGC)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: Ilib::ICreateGC()");
    {
	Ilib__IGC	RETVAL;
#line 229 "Ilib.xs"
	RETVAL = ICreateGC ();
#line 330 "Ilib.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Ilib::IGC", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_IAllocColor)
{
    dXSARGS;
    if (items != 3)
	croak("Usage: Ilib::IAllocColor(red, green, blue)");
    {
	unsigned int	red = (unsigned int)SvUV(ST(0));
	unsigned int	green = (unsigned int)SvUV(ST(1));
	unsigned int	blue = (unsigned int)SvUV(ST(2));
	Ilib__IColor	RETVAL;
#line 239 "Ilib.xs"
	RETVAL = IAllocColor ( red, green, blue );
#line 349 "Ilib.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Ilib::IColor", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_IAllocNamedColor)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Ilib::IAllocNamedColor(colorname)");
    {
	char *	colorname = (char *)SvPV(ST(0),PL_na);
	Ilib__IColor	RETVAL;
#line 247 "Ilib.xs"
	{
		IColor ret;
		IAllocNamedColor ( colorname, &ret );
		RETVAL = ret;
	}
#line 370 "Ilib.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Ilib::IColor", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_ISetBackground)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Ilib::ISetBackground(gc, color)");
    {
	Ilib__IGC	gc;
	Ilib__IColor	color;
	unsigned int	RETVAL;

	if (sv_derived_from(ST(0), "Ilib::IGC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gc = (Ilib__IGC) tmp;
	}
	else
	    croak("gc is not of type Ilib::IGC");

	if (sv_derived_from(ST(1), "Ilib::IColor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    color = (Ilib__IColor) tmp;
	}
	else
	    croak("color is not of type Ilib::IColor");
#line 260 "Ilib.xs"
	RETVAL = ISetBackground ( gc, color );
#line 402 "Ilib.c"
	ST(0) = sv_newmortal();
	sv_setuv(ST(0), (UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_IFillRectangle)
{
    dXSARGS;
    if (items != 6)
	croak("Usage: Ilib::IFillRectangle(image, gc, x, y, width, height)");
    {
	Ilib__IImage	image;
	Ilib__IGC	gc;
	int	x = (int)SvIV(ST(2));
	int	y = (int)SvIV(ST(3));
	unsigned int	width = (unsigned int)SvUV(ST(4));
	unsigned int	height = (unsigned int)SvUV(ST(5));
	unsigned int	RETVAL;

	if (sv_derived_from(ST(0), "Ilib::IImage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    image = (Ilib__IImage) tmp;
	}
	else
	    croak("image is not of type Ilib::IImage");

	if (sv_derived_from(ST(1), "Ilib::IGC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    gc = (Ilib__IGC) tmp;
	}
	else
	    croak("gc is not of type Ilib::IGC");
#line 273 "Ilib.xs"
	RETVAL = IFillRectangle ( image, gc, x, y, width, height );
#line 438 "Ilib.c"
	ST(0) = sv_newmortal();
	sv_setuv(ST(0), (UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_ISetForeground)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Ilib::ISetForeground(gc, color)");
    {
	Ilib__IGC	gc;
	Ilib__IColor	color;
	unsigned int	RETVAL;

	if (sv_derived_from(ST(0), "Ilib::IGC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    gc = (Ilib__IGC) tmp;
	}
	else
	    croak("gc is not of type Ilib::IGC");

	if (sv_derived_from(ST(1), "Ilib::IColor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    color = (Ilib__IColor) tmp;
	}
	else
	    croak("color is not of type Ilib::IColor");
#line 282 "Ilib.xs"
	RETVAL = ISetForeground ( gc, color );
#line 470 "Ilib.c"
	ST(0) = sv_newmortal();
	sv_setuv(ST(0), (UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_ILoadFontFromFile)
{
    dXSARGS;
    if (items != 3)
	croak("Usage: Ilib::ILoadFontFromFile(name, path, font_return)");
    {
	char *	name = (char *)SvPV(ST(0),PL_na);
	char *	path = (char *)SvPV(ST(1),PL_na);
	void	unsigned int	RETVAL;
#line 292 "Ilib.xs"
	RETVAL = ILoadFontFromFile ( name, path, &font_return );
#line 488 "Ilib.c"
	ST(0) = sv_newmortal();
	sv_setuv(ST(0), (UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Ilib_IImage_DESTORY)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Ilib::IImage_DESTORY(image)");
    {
	Ilib__IImage	image;

	if (sv_derived_from(ST(0), "Ilib::IImage")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    image = (Ilib__IImage) tmp;
	}
	else
	    croak("image is not of type Ilib::IImage");
#line 300 "Ilib.xs"
	_IFreeImage ( image );
#line 511 "Ilib.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ilib)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Ilib::constant", XS_Ilib_constant, file);
        newXS("Ilib::str_constant", XS_Ilib_str_constant, file);
        newXS("Ilib::IErrorString", XS_Ilib_IErrorString, file);
        newXS("Ilib::ICreateImage", XS_Ilib_ICreateImage, file);
        newXS("Ilib::IWriteImageFile", XS_Ilib_IWriteImageFile, file);
        newXS("Ilib::ICreateGC", XS_Ilib_ICreateGC, file);
        newXS("Ilib::IAllocColor", XS_Ilib_IAllocColor, file);
        newXS("Ilib::IAllocNamedColor", XS_Ilib_IAllocNamedColor, file);
        newXS("Ilib::ISetBackground", XS_Ilib_ISetBackground, file);
        newXS("Ilib::IFillRectangle", XS_Ilib_IFillRectangle, file);
        newXS("Ilib::ISetForeground", XS_Ilib_ISetForeground, file);
        newXS("Ilib::ILoadFontFromFile", XS_Ilib_ILoadFontFromFile, file);
        newXS("Ilib::IImage_DESTORY", XS_Ilib_IImage_DESTORY, file);
    XSRETURN_YES;
}

